### ISSUE TITLE
Segmentation fault (core dumped) on consumer run

### ISSUE THREAD

**Issue by seyfer** [prolic/HumusAmqpModule#33] opened 2016-03-04 08:17 UTC
Spotted on different servers

one
```
php -v
PHP 5.6.18 (cli) (built: Feb  3 2016 12:50:09) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

```
two
```
php -v
PHP 5.6.18-1+deb.sury.org~wily+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

Queues is registered in rabbit. Messages was added successful, but consumer fails.
Our command to run looks like this

```
/usr/bin/php /home/project/public/index.php humus amqp consumer reporting.history.cpm.consumer
```

strace output below

```
open("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/QueueFactoryInterface.php", O_RDONLY) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=1355, ...}) = 0
fstat(7, {st_mode=S_IFREG|0644, st_size=1355, ...}) = 0
fstat(7, {st_mode=S_IFREG|0644, st_size=1355, ...}) = 0
mmap(NULL, 1355, PROT_READ, MAP_SHARED, 7, 0) = 0x7f9bb8e92000
stat("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/QueueFactoryInterface.php", {st_mode=S_IFREG|0644, st_size=1355, ...}) = 0
fcntl(3, F_SETLKW, {type=F_WRLCK, whence=SEEK_SET, start=0, len=1}) = 0
fcntl(3, F_SETLK, {type=F_UNLCK, whence=SEEK_SET, start=0, len=1}) = 0
munmap(0x7f9bb8e92000, 1355)            = 0
close(7)                                = 0
sendto(6, "\1\0\1\0\0\0!\0002\0\n\0\0\25reporting.history."..., 41, MSG_NOSIGNAL, NULL, 0) = 41
recvfrom(6, 0x2c672b0, 131072, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}], 1, -1)    = 1 ([{fd=6, revents=POLLIN}])
recvfrom(6, "\1\0\1\0\0\0\"\0002\0\v\25reporting.history.cp"..., 131072, 0, NULL, NULL) = 42
sendto(6, "\1\0\1\0\0\0004\0002\0\24\0\0\25reporting.history."..., 60, MSG_NOSIGNAL, NULL, 0) = 60
recvfrom(6, 0x2c672b0, 131072, 0, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=6, events=POLLIN}], 1, -1)    = 1 ([{fd=6, revents=POLLIN}])
recvfrom(6, "\1\0\1\0\0\0\4\0002\0\25\316", 131072, 0, NULL, NULL) = 12
lstat("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php", {st_mode=S_IFREG|0644, st_size=11161, ...}) = 0
lstat("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/project/vendor/prolic/humus-amqp-module/src", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/project/vendor/prolic/humus-amqp-module", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/project/vendor/prolic", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php", {st_mode=S_IFREG|0644, st_size=11161, ...}) = 0
lstat("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/project/vendor/prolic/humus-amqp-module/src", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/project/vendor/prolic/humus-amqp-module", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/project/vendor/prolic", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php", O_RDONLY) = 7
fstat(7, {st_mode=S_IFREG|0644, st_size=11161, ...}) = 0
fstat(7, {st_mode=S_IFREG|0644, st_size=11161, ...}) = 0
fstat(7, {st_mode=S_IFREG|0644, st_size=11161, ...}) = 0
mmap(NULL, 11161, PROT_READ, MAP_SHARED, 7, 0) = 0x7f9ba072a000
stat("/home/project/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php", {st_mode=S_IFREG|0644, st_size=11161, ...}) = 0
fcntl(3, F_SETLKW, {type=F_WRLCK, whence=SEEK_SET, start=0, len=1}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by seyfer** [comment] 2016-03-04 08:20
rabbit versions

one
`RabbitMQ 3.5.6, Erlang R14B04`

two
`RabbitMQ 3.5.4, Erlang 18.0`

**Comment by seyfer** [comment] 2016-03-04 08:22
Our config

```
<?php

return [
    'humus_amqp_module' => [
        'exchanges'       => [
            'reporting.history' => [
                'name' => 'reporting.history',
                'type' => 'direct',
            ],
        ],
        'queues'          => [
            'reporting.history.cpm' => [
                'name'         => 'reporting.history.cpm',
                'exchange'     => 'reporting.history',
                'routing_keys' => [

                ],
            ],
        ],
        'producers'       => [
            'reporting.history.cpm.producer' => [
                'exchange'          => 'reporting.history',
                'auto_setup_fabric' => true
            ],
        ],
        'consumers'       => [
            'reporting.history.cpm.consumer' => [
                'queues'            => [
                    'reporting.history.cpm'
                ],
                'auto_setup_fabric' => true,
                'callback'          => 'application.application.HistoryCpm.consumer.HistoryCpmConsumer',
                'logger'            => 'reporting.history.cpm.consumer.logger',
            ],
        ],
        'connections'     => [
            'default' => [
                'host'       => 'localhost',
                'port'       => 5672,
                'login'      => 'login',
                'password'   => 'password',
                'vhost'      => '/',
                'persistent' => true,
            ],
        ],
        'plugin_managers' => [
            'callback' => [
                'factories' => [
                    'application.application.HistoryCpm.consumer.HistoryCpmConsumer' => \Application\Application\HistoryCpm\Consumer\HistoryCpmConsumerFactory::class,
                ],
            ],
        ],
    ]
];
```

**Comment by seyfer** [comment] 2016-03-04 08:32
There is my core dump

```
gdb /usr/bin/php /home/seyfer/core_dumps/core-php.4177
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/php...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 4177]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php ./public/index.php humus amqp consumer reporting.history.cpm.consumer'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000006db444 in _zval_ptr_dtor ()
```

**Comment by seyfer** [comment] 2016-03-04 08:50
Also I have posted issue to php bugs

https://bugs.php.net/bug.php?id=71710

**Comment by prolic** [comment] 2016-03-04 12:50
This is not a PHP-Bug, I would close the issue on php.net.

Can you please give me your librabbitmq-c version and php amqp version?

**Comment by seyfer** [comment] 2016-03-04 13:19
How I can get this versions? With which commands ?

**Comment by prolic** [comment] 2016-03-04 13:23
php -i | grep librabbitmq
php -r "echo phpversion('amqp');"

**Comment by seyfer** [comment] 2016-03-04 13:33
one
```
php -i | grep librabbitmq
librabbitmq version => 0.7.1

php -r "echo phpversion('amqp');"
1.6.1
```

two
```
[seyfer@seed]: ~ php -i | grep librabbitmq
librabbitmq version => 0.5.2
[seyfer@seed]: ~ php -r "echo phpversion('amqp');"
1.6.0
```

**Comment by prolic** [comment] 2016-03-04 13:35
librabbitmq 0.7.1 should be good, 0.5.2 is a little old, i would recommend updating this one.

also install v1.7.0alpha2, this is much more mature, and a lot of segfaults are gone in this release.

**Comment by prolic** [comment] 2016-03-04 13:35
with v1.7.0alpha2 i mean ext-amqp :)

**Comment by prolic** [comment] 2016-03-04 13:39
sudo pecl install amqp-alpha

**Comment by prolic** [comment] 2016-03-04 13:40
btw: i am working on a framework independent rewrite of HumusAmqpModule (see: https://github.com/prolic/HumusAmqp). This will be PHP 7 only and have some additional nice features as well :)

**Comment by seyfer** [comment] 2016-03-04 13:46
I think this is not good idea - php7 only, at least 3-5 years major users will be still php5 users because old projects suppot, Even new projects still start with php5.

I will try fix this with command
`sudo pecl install amqp-alpha`

local and on server. Thank you!

**Comment by prolic** [comment] 2016-03-04 14:04
PHP 5.6 active support ends 31 Dec 2016, security support ends 31 Dec 2018.

**Closed by prolic** 2016-03-04 14:04 UTC
Labels: question

**Comment by prolic** [comment] 2016-03-04 15:53
Please notify if the upgrade of ext-amqp resolved the issue.

**Comment by seyfer** [comment] 2016-03-05 04:53
I have updated to amqp-alpha and consumer starts to work, but now php5-fpm starts to crash periodically 
I can't copy error, there is a screenshot
[https://www.dropbox.com/s/mq1l56vg93t9vlo/Screenshot%20from%202016-03-05%2011-51-08.png?dl=0](url)

**Comment by seyfer** [comment] 2016-03-05 08:04
@prolic , you are right about php 5.6 support ending in 2016.
But usage statistics in reality is very different
2015 year stats
https://seld.be/notes/php-versions-stats-2015-edition
2016 year fresh stats
http://w3techs.com/technologies/details/pl-php/5/all

I don't think this percentages will change significantly in 2016, even for versions without support.

**Comment by prolic** [comment] 2016-03-05 13:22
This seems to be a problem with php-amqp extension. Please open an issue at https://github.com/pdezwart/php-amqp/. Try to give a way, how to reproduce this issue.

**Comment by jeremymills** [comment] 2016-04-06 18:18
Stumbled upon this issue while running in to the same problem on php5.6.18... the `sudo pecl install amqp-alpha` command fixed this for me, hope this helps anyone who finds this as well
